Added macOS shortcut documentation
FreeTubeApp/FreeTube-Docs pull request #112
Opened 2023-12-01 22:30 UTC by OblackatO

As promised the documentation for macOS shortcut. 

For some reason the images aren't appearing... I added two images in ../images/, where ../ is the relative path to the *usage* folder. 

Could you please fix this or move the images to where they should be at? 
I also tried to create an *usage_images* folder under *usage*, but that also didn't work.

2023-12-02 03:20 UTC, PikachuEXE requested changes
I tried this and it works locally

[Doc for using images/assets in `jekyll`](https://jekyllrb.com/docs/posts/)

Please also change the `alt text` to something useful (just need short description)

2023-12-02 03:20 UTC, PikachuEXE commented on usage/macos-shortcut.md
> +    ![alt text](../images/ShortcutMacOS.png)
```suggestion
    ![alt text](/images/ShortcutMacOS.png)
```

2023-12-02 03:20 UTC, PikachuEXE commented on usage/macos-shortcut.md
> +    ![alt text](../images/ShortcutKeybind.png)
```suggestion
    ![alt text](/images/ShortcutKeybind.png)
```

2023-12-03 18:56 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented on usage/macos-shortcut.md
> +**NOTE:**
```suggestion
**Note:**
```

2023-12-03 18:57 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented on usage/macos-shortcut.md
> +- FreeTube doesn't need to be opened in order for the shortcut to be run.
```suggestion
- FreeTube doesn't need to be opened in order to run the shortcut.
```

2023-12-03 18:57 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented on usage/macos-shortcut.md
> +- MacOS updates might remove the shortcut keybinding.
```suggestion
- macOS updates might remove the shortcut keybinding.
```

2023-12-03 19:02 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
Maybe we add a link for users that are looking at https://docs.freetubeapp.io/usage/browser-extension/ to this new page so they dont miss out on this info

2023-12-04 20:38 UTC, efb4f5ff-1298-471a-8973-3d47447115dc approved these changes

2023-12-11 12:43 UTC, ChunkyProgrammer approved these changes

2023-12-11 12:43 UTC, merged