Update instruction for "Install Dependencies"
FreeTubeApp/FreeTube-Docs pull request #16
Opened 2021-09-16 01:51 UTC by PikachuEXE

This is to update `npm > yarn` switch for package installation step in
https://github.com/FreeTubeApp/FreeTube/pull/1692

This should **not** be merged until the above PR is merged

2021-09-19 07:52 UTC, efb4f5ff-1298-471a-8973-3d47447115dc approved these changes

2021-09-19 08:58 UTC, PikachuEXE commented
The related PR is now merged so this PR can be merged now

2021-09-19 10:24 UTC, peepopoggers submitted a review, later dismissed

2021-09-19 13:53 UTC, jasonhenriquez requested changes

2021-09-19 13:53 UTC, jasonhenriquez commented on development/getting-started.md
> +yarn install
Isn't it just `yarn`?

2021-09-20 02:13 UTC, PikachuEXE commented on development/getting-started.md
> +yarn install
Fine I will include both -,-

2021-09-20 02:14 UTC, PikachuEXE commented
Updated!

2021-09-20 08:08 UTC, Hiers approved these changes
Instructions worked on my machine, seems good.

2021-09-20 11:24 UTC, peepopoggers approved these changes
Looking yarn good :+1:

2021-09-20 16:12 UTC, jasonhenriquez approved these changes
Nice job stitching this together!

2021-09-20 16:12 UTC, merged