Update keyboard shortcuts description
FreeTubeApp/FreeTube-Docs pull request #23
Opened 2022-05-23 13:52 UTC by efb4f5ff-1298-471a-8973-3d47447115dc

I was confused by some descriptions so i (tried) to clarify them

2022-05-24 05:42 UTC, PikachuEXE submitted a review, later dismissed

2022-05-30 14:02 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
Todo: update shortcut added in https://github.com/FreeTubeApp/FreeTube/pull/2221

2022-05-30 15:25 UTC, absidue requested changes
The previous and next shortcuts are playlist only, I feel like this should be specified

2022-05-30 15:25 UTC, absidue commented on usage/keyboard-shortcuts.md
> +| Previous or Next | Skips to the Previous / Next video |
```suggestion
| Previous or Next | Skips to the Previous / Next video in a playlist |
```

2022-05-31 01:44 UTC, PikachuEXE approved these changes
So many keyboard shortcuts...

2022-05-31 18:26 UTC, absidue approved these changes

2022-06-02 15:59 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
@ChunkyProgrammer 😬

2022-06-02 16:47 UTC, merged