Include LibRedirect in docs
FreeTubeApp/FreeTube-Docs pull request #32
Opened 2022-08-02 20:58 UTC by efb4f5ff-1298-471a-8973-3d47447115dc

closes #20

Approve when https://github.com/FreeTubeApp/FreeTube/pull/2437 is merged

2022-08-07 09:49 UTC, absidue requested changes

2022-08-07 09:49 UTC, absidue commented on usage/browser-extension.md
> +FreeTube is supported by the [Privacy Redirect](https://github.com/SimonBrazell/privacy-redirect) and [LibRedirect](https://github.com/libredirect/libredirect) extension, which will allow you to open
```suggestion
FreeTube is supported by the [Privacy Redirect](https://github.com/SimonBrazell/privacy-redirect) and [LibRedirect](https://github.com/libredirect/libredirect) extensions, which will allow you to open YouTube links into FreeTube. You must enable the option within the advanced settings for it to work.
```

2022-08-07 17:45 UTC, absidue approved these changes

2022-08-08 01:51 UTC, PikachuEXE approved these changes

2022-08-10 03:27 UTC, ChunkyProgrammer approved these changes

2022-08-10 03:27 UTC, merged